# Generated by Buildr 1.3.5, change to your liking
# Version number for this release
VERSION_NUMBER = "0.9.0"
# Group identifier for your projects
GROUP = "shawty"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"

desc "The Shawty text extractor."

require 'buildr/groovy'

# If I don't do this test.compile fails :( 
Java.classpath << "junit:junit:jar:4.8.1"

define "shawty" do
  manifest["Implementation-Vendor"] = COPYRIGHT
  project.version = VERSION_NUMBER
  project.group = GROUP
  test.resources
end
